sys = require 'sys'
exec = (require 'child_process').exec

FILENAME = '../javascript/game'
FILES = [
  'kwing/lib/vector.coffee',
  'kwing/lib/array.coffee',
  'kwing/lib/timer.coffee',
  'kwing/lib/jukebox.coffee',
  'main.coffee',
  'Classes/gameobject.coffee',
  'Classes/character.coffee',
  'Classes/player.coffee',
  'Classes/tile.coffee',
  'Classes/tileset.coffee',
  'Classes/map.coffee',
  'Classes/mainscene.coffee',
  'Classes/logoscene.coffee',
]
HTMLFILE = 'index.html'

task 'compile', 'compile and minify Jubiol.', (options) ->
  outputErr = (err, stdout, stderr) ->
    throw err if err
    if stdout or stderr
      console.log "#{stdout} #{stderr}"
  if FILES.length is 1
    exec "coffee -c #{FILENAME}.js #{FILES[0]}", outputErr
  else
    exec "coffee -cj #{FILENAME} #{FILES.join ' '}", outputErr
  exec "yuicompressor #{FILENAME}.js > #{FILENAME}.min.js", outputErr